### ISSUE TITLE
Bug in `simultaneous_steane_code`

### ISSUE THREAD

**Issue by gnperdue** [Lopez-Santi/QEC_code#28]
If you run the `03. Stabilizer Codes and Steane Code.ipynb`, the code fails at the end:

```
line 448, in simultaneous_steane_code
    if bits[8] == '1':
IndexError: index 8 is out of bounds for axis 0 with size 8
```

Indeed, the `bits` array seems to always be of size 8. I think we meant to check something indexed to the total number of qubits?

**Comment by Lopez-Santi** [comment]
This should now be resolved. It was a minor issue with the vector_state_to_bit_state call where we had "10" instead of "13" which is the correct number of qubits.

**Comment by Lopez-Santi** [comment]
Should now be pushed to main.

**Comment by gnperdue** [comment]
Actually, the error still occurs. If you run `03. Stabilizer Codes and Steane Code.ipynb`, the last cell still fails with the same error.

I started the process of adding some unit tests in #29 - if you do `python run_tests.py` in the project root that will recreate the error without any need to launch Jupyter or step through any of the extra cells in a notebook.

**Comment by gnperdue** [comment]
May have fixed this with #49 @Lopez-Santi (still need to write some tests, but I fixed the crash)

**Comment by gnperdue** [comment]
This is verified fixed.
